# name: Generate Podcast

# on:
#   schedule:
#     - cron: '0 7,13,19 * * *'  # اجرا در ساعت ۷، ۱۳، ۱۹ UTC
#   workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GATEWAY_TOKEN: ${{ secrets.GATEWAY_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GH_REPO: YourNewsSystem/podcasts
      CATEGORY: sport

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Podcast Generator
        run: python script/main.py
